<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{

    public function updateProfileApi(Request $request)
    {
        $user = $request->user();

        // Validate the incoming data
        $validatedData = $request->validate([
            'name' => 'required|string|max:255',
            'email' => [
                'required',
                'string',
                'email',
                'max:255',
                Rule::unique('users')->ignore($user->id),
            ],
            'user_image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048', // Max 2MB
        ]);

        // Handle the file upload
        if ($request->hasFile('user_image')) {
            // Delete the old image if it exists
            if ($user->user_image) {
                Storage::disk('public')->delete($user->user_image);
            }
            // Store the new image and get its path
            $path = $request->file('user_image')->store('profile_images', 'public');
            $user->user_image = $path;
        }

        // Update name and email
        $user->name = $validatedData['name'];
        $user->email = $validatedData['email'];
        $user->save();

        // Return a success response using the UserResource for consistency
        return response()->json([
            'message' => 'Profile updated successfully!',
            'user' => $user->fresh(),
        ]);
    }

    public function getEnrolledCoursesApi(Request $request)
    {
        $user = $request->user();
        if (!$user) {
            return response()->json(['message' => 'Unauthenticated.'], 401);
        }

        $courses = $user->courses()->get()->map(function($course) {
            return [
                'id' => $course->id,
                'name' => $course->course_name,
                'hours' => $course->course_hour,
                'price' => $course->course_price,
                'type' => $course->course_type,
                'description' => $course->description,
                'thumbnail' => $course->thumbnail_url, // Correctly uses the accessor
            ];
        });

        return response()->json(['data' => $courses]);
    }

    public function getEnrolledCourseIdsApi(Request $request)
    {
        $user = $request->user();
        if (!$user) {
            return response()->json(['message' => 'Unauthenticated.'], 401);
        }
        $enrolledCourseIds = $user->courses()->pluck('course.id');
        return response()->json(['data' => $enrolledCourseIds]);
    }

    public function getActivityStatsApi(Request $request)
    {
        $user = $request->user();
        if (!$user) {
            return response()->json(['message' => 'Unauthenticated.'], 401);
        }

        $certificateCount = $user->certificates()->count();
        $completedCount = $certificateCount;
        $totalEnrolledCount = $user->courses()->count();
        $incompleteCount = $totalEnrolledCount - $completedCount;

        return response()->json([
            'incomplete' => $incompleteCount,
            'completed' => $completedCount,
            'certificates' => $certificateCount,
        ]);
    }

    public function getUserProfile(Request $request)
    {
        $user = $request->user();
        if (!$user) {
            return response()->json(['message' => 'Unauthenticated.'], 401);
        }

        // Return only the specified fields.
        // The 'user_image_url' is automatically generated by the accessor in your User model.
        return response()->json([
            'name' => $user->name,
            'email' => $user->email,
            'user_image_url' => $user->user_image_url,
        ]);
    }
}